### ISSUE TITLE
Peer to Peer Morning Session Code Review

### ISSUE THREAD

**Issue by samwel-mongare** [Mosams/to-do-list#2]

**Comment by anuarshaidenov** [comment]
### Well done Sam, your code looks great however there are some issues to point out:
- When an item gets checked the change doesn't get displayed

**Comment by Hombre2014** [comment]
## Very good job overall.
- All the JavaScript code is in one file - index.js. You can split the file into three as per requirements and then import the necessary functions and variables into index.js file.

**Comment by kingqabil** [comment]
**Nice Job Sam, keep the good coding:**

- Add a new JavaScript files and import it as a module

**Comment by samwel-mongare** [comment]
Thanks for the review @Hombre2014  , @anuarshaidenov , @kingqabil  . I have implemented all the suggestions.
